version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - "> 4.4.6, < 4.5"
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - "> 4.4.4, < 5"
  - dependency-name: "@vue/cli-service"
    versions:
    - "> 4.4.6, < 4.5"
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
    - 3.9.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.9
